### PR TITLE
Zillow CSVs

### PR DESCRIPTION
**Pull request by iceicelogan**
I found a bunch of Zillow Data that we can do some magical things with!

### CODE REVIEW

**Review by tlj4k8 — CHANGES_REQUESTED** [review]
Exciting! Can we put all of these into one folder and name it lie `data` or whatever feels right to keep in all in one place?

**Comment by iceicelogan** [comment]
> Exciting! Can we put all of these into one folder and name it lie `data` or whatever feels right to keep in all in one place?

Yep! One moment, @tlj4k8

**Comment by iceicelogan** [comment]
@tlj4k8 check iit out now. All of the files are in `data`

**Review by tlj4k8 — APPROVED** [review]
🏅 Perfect! All in one place I love it!

**Pull request merged**
